version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: togglex
      POSTGRES_PASSWORD: togglex
      POSTGRES_DB: togglex
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
volumes:
  pgdata:
  redisdata:
